config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ registrations: "registrations" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :api do
    scope "v1", module: :v1 do # defaults: {format: :json} perhaps?
      resources :causes, only: [:index, :show, :create, :update, :destroy]
      resources :charities, except: [:new, :edit] do
        # :index is not needed because you can show a charity to see its
        # causes. This does not create a cause, though; this merely associates
        # an existing cause with the charity:
        resources :causes, only: [:create, :destroy]
      end
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ::NonRailsAdminApplicationController
  skip_authorization_check
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2>Hello World; I'm givegivegave</h2>
<p>
  The time is now: <%= Time.now %>
</p>
<p>
  This might be a good time to <%= link_to "sign out", destroy_user_session_path, :method => :delete %> or <%= link_to "sign in", new_user_session_path %>
</p>
<p>
  The only views we've got for you are the <%= link_to "list of charities",
  api_charities_path %> and the <%= link_to "list of causes",  api_causes_path %>
</p>
<% if can? :dashboard, nil %>
<p>
  You are an admin so you can use <%= link_to "rails_admin",  rails_admin_path %>
</p>
<% end %>